apiVersion: v1
kind: Service
metadata:
  name: render-poetisa
  labels:
    app: render-poetisa
spec:
  selector:
    app: render-poetisa
  ports:
  - name: "80"
    port: 80
    targetPort: 80
    nodePort: 30501
  type: "NodePort"
  